from typing import Any, List, Tuple, Union

from . rect import Rect
from . surface import Surface


def init() -> None: ...
def quit() -> None: ...
def get_init() -> bool: ...
def set_mode(resolution: Tuple[int, int]=(0, 0), flags: Any=0, depth: Any=0) -> Surface: ...
def get_surface() -> Surface: ...
def flip() -> None: ...
def update(rect: Union[Rect, List[Rect]]) -> None: ...
def get_driver() -> str: ...
def get_active() -> bool: ...
def set_icon(Surface) -> None: ...
def set_caption(title: str, icontitle: str=None) -> None: ...
def get_caption() -> Tuple[str, str]: ...


# vim: set filetype=python :
