from typing import Tuple


def get_pressed() -> Tuple[int, int, int]: ...
def get_pos() -> Tuple[int, int]: ...
def get_rel() -> Tuple[int, int]: ...
def set_pos(pos: Tuple[int, int]) -> None: ...
def get_focused() -> bool: ...


# vim: set filetype=python :
