from typing import Iterable

from . rect import Rect


class Sprite:
    def __init__(self, *groups: Group) -> None:
        self.rect = None # type: Rect
    def get_rect(self) -> Rect: ...
    def add(self, *groups: Group) -> None: ...
    def kill(self) -> None: ...
    def spritecollideany(sprite: "Sprite", group: Group, collided: Any) -> Optional[Sprite]: ...



class Group:
    def __init__(self) -> None: ...
    def add(self, *sprites: Sprite) -> None: ...
    def update(self, *args) -> None: ...
    def draw(self, Surface) -> None: ...
    def __iter__(self) -> Iterable[Sprite]: ...
    def __next__(self) -> Sprite: ...


# vim: set filetype=python :
