from typing import Any, Optional, Tuple, Union

from . rect import Rect


HWSURFACE = None # type: Any
SRCALPHA = None # type: Any


class Surface:
    def __init__(self, area: Tuple[int, int], flags: int=0, depth: int=0, masks: Any=None) -> None: ...
    def blit(self, surf: "Surface", dest: Union[Rect, Tuple[int, ...]], area: Union[Rect, Tuple[int, ...]]=None, special_flags: Any=0) -> None: ...
    def convert(self) -> "Surface": ...
    def copy(self) -> "Surface": ...
    def fill(self,
        color: Tuple[Any, ...],
        rect: Rect=None,
        special_flags: Any=0) -> None: ...
    def get_rect(self, **kwargs) -> Rect: ...
    def set_colorkey(self, color: Tuple[int, int, int], flags: Any=0) -> None: ...

# vim: set filetype=python :
